In [1]:
import pandas as pd
import os
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import re

from pyspark.ml.recommendation import ALS
from pyspark.ml.feature import Tokenizer, StopWordsRemover,StringIndexer
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.mllib.evaluation import RankingMetrics

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

In [4]:
meta_schema = StructType([
    StructField("main_category", StringType(), True),
    StructField("title", StringType(), True),
    StructField("average_rating", DoubleType(), True),
    StructField("rating_number", LongType(), True),
    StructField("features", ArrayType(StringType()), True),
    StructField("description", ArrayType(StringType()), True),
    StructField("price", DoubleType(), True),
    StructField("images", ArrayType(MapType(StringType(), StringType())), True),
    StructField("videos", ArrayType(MapType(StringType(), StringType())), True),
    StructField("store", StringType(), True),
    StructField("categories", ArrayType(StringType()), True),

    StructField("details", StringType(), True),

    StructField("parent_asin", StringType(), True),
    StructField("bought_together", DoubleType(), True),
    StructField("subtitle", StringType(), True),
    StructField("author", StringType(), True),
])
raw_meta_df = spark.read.text("/content/drive/MyDrive/data - MoMD/meta_Office_Products.jsonl")
meta_df = (
    raw_meta_df
    .select(from_json(col("value"), meta_schema).alias("data"))
    .select("data.*")
)

In [5]:
df_data = spark.read.format("json").option("inferSchema", "true").option("header", "true").load("/content/drive/MyDrive/data - MoMD/Office_Products.jsonl")

In [ ]:
df_data.show()

+----------+------------+--------------------+-----------+------+--------------------+-------------+--------------------+--------------------+-----------------+
|      asin|helpful_vote|              images|parent_asin|rating|                text|    timestamp|               title|             user_id|verified_purchase|
+----------+------------+--------------------+-----------+------+--------------------+-------------+--------------------+--------------------+-----------------+
|B01AHHL4X2|           0|                  []| B01MZ3SD2X|   5.0|Lovely ink. Write...|1677939345945| Pretty & I love it!|AFKZENTNBQ7A7V7UX...|             true|
|B08L6H23JZ|           0|                  []| B08L6H23JZ|   4.0|Overall I’m prett...|1677939160682|2 excellent 1 ext...|AFKZENTNBQ7A7V7UX...|             true|
|B07JDZ5J46|           2|                  []| B07JDZ5J46|   1.0|[[VIDEOID:63276c1...|1660188831933|I don’t get the r...|AFKZENTNBQ7A7V7UX...|             true|
|B004MNX7EW|           0|[{IMAGE, https://...| B07BR2PBJN|   4.0|It’s a beautiful ...|1659806066713|Ordering Ink onli...|AFKZENTNBQ7A7V7UX...|             true|
|B019YLRFFS|           0|                  []| B097SFY5ZS|   3.0|Idk if I just got...|1659799390978|Mine are iffy at ...|AFKZENTNBQ7A7V7UX...|             true|
|B0025ZTNA6|           0|[{IMAGE, https://...| B003UBTODA|   3.0|First time I’ve t...|1657591253115|          Mine skips|AFKZENTNBQ7A7V7UX...|             true|
|B00IM4E0WK|           0|[{IMAGE, https://...| B09S7B2FMQ|   3.0|Great paper. I ow...|1655240303599|Arrived damaged! ...|AFKZENTNBQ7A7V7UX...|             true|
|B08Z78C8K2|           0|[{IMAGE, https://...| B08Z78C8K2|   3.0|[[VIDEOID:ffd2a83...|1654452995581|Quality not as pi...|AFKZENTNBQ7A7V7UX...|             true|
|B00KG08EYS|           0|[{IMAGE, https://...| B0B6BSZ6DJ|   4.0|Literally one of ...|1645819690591|Packing is awful ...|AFKZENTNBQ7A7V7UX...|             true|
|B09FPQXH6B|           0|[{IMAGE, https://...| B09FPQXH6B|   3.0|[[VIDEOID:c4ffdd9...|1645518946029|Defective hardwar...|AFKZENTNBQ7A7V7UX...|            false|
|B07YFCV1NV|           1|[{IMAGE, https://...| B07YFCV1NV|   3.0|[[VIDEOID:b5de3fb...|1644694360570|My pen is utter g...|AFKZENTNBQ7A7V7UX...|            false|
|B00006IBQG|           0|[{IMAGE, https://...| B00006IBQG|   3.0|I’ve used Carter’...|1644057297504|Damaged! Stamps d...|AFKZENTNBQ7A7V7UX...|             true|
|B00FWRVUJ6|           0|[{IMAGE, https://...| B00YL5GBWG|   4.0|New to this brand...|1643161893294|Excellent! Buy it...|AFKZENTNBQ7A7V7UX...|             true|
|B08L4K4QKR|           0|[{IMAGE, https://...| B08L4K4QKR|   3.0|Update: received ...|1643160661334|Could have been w...|AFKZENTNBQ7A7V7UX...|             true|
|B09KLJ9NJH|           0|[{IMAGE, https://...| B09KLJ9NJH|   4.0|It’s a nice heavy...|1642826493637|Lovely, but front...|AFKZENTNBQ7A7V7UX...|             true|
|B06XY7YNHG|           0|[{IMAGE, https://...| B06XY7YNHG|   5.0|My review is whac...|1642733588149|       Wrong pens!!!|AFKZENTNBQ7A7V7UX...|             true|
|B09MD52PRY|           1|[{IMAGE, https://...| B0B5RTTZ95|   3.0|It’s pretty, but ...|1642564061814|Arrived dinged up...|AFKZENTNBQ7A7V7UX...|             true|
|B07T4NX5F6|           0|                  []| B07T4NX5F6|   5.0|I’m a book freak ...|1624656029309|Pretty Flipping A...|AFKZENTNBQ7A7V7UX...|             true|
|B08XMQTLG4|          15|                  []| B08XM9Y46P|   5.0|It’s beautiful. I...|1624655605692|First one mis-del...|AFKZENTNBQ7A7V7UX...|             true|
|B07NWP25SX|           0|                  []| B07NWP25SX|   5.0|It’s pretty. The ...|1624654944258|          I love it!|AFKZENTNBQ7A7V7UX...|             true|
+----------+------------+--------------------+-----------+------+--------------------+-------------+--------------------+--------------------+-----------------+
only showing top 20 rows

In [ ]:
meta_df.show()

+--------------------+--------------------+--------------+-------------+---------------------+--------------------+------+--------------------+--------------------+--------------------+--------------------+--------------------+-----------+---------------+--------------------+------+
|       main_category|               title|average_rating|rating_number|             features|         description| price|              images|              videos|               store|          categories|             details|parent_asin|bought_together|            subtitle|author|
+--------------------+--------------------+--------------+-------------+---------------------+--------------------+------+--------------------+--------------------+--------------------+--------------------+--------------------+-----------+---------------+--------------------+------+
|     Office Products|Alliance Rubber 0...|           4.5|          665| [REUSABLE: These ...|[Alliance Rubber ...|  2.68|[{thumb -> https:...|[{title -> AMUU r...|            Alliance|[Office Products,...|{"Manufacturer":"...| B001S28Q4Q|           NULL|                NULL|  NULL|
|     Office Products|10 Set Mini Offic...|           3.3|          186| [Made of high qua...|[Whether you're a...| 13.99|[{thumb -> https:...|[{title -> Small ...|              Chneeu|[Office Products,...|{"Manufacturer":"...| B07RPQVH21|           NULL|                NULL|  NULL|
|     Office Products|Creanoso Humorous...|           4.6|          100| [Creanoso Bookish...|                  []|  9.99|[{thumb -> https:...|[{title -> Cool S...|            Creanoso|[Office Products,...|{"Manufacturer":"...| B07J58B87Q|           NULL|                NULL|  NULL|
|     All Electronics|PenPower WorldPen...|           3.9|          296| [TEXT TO SPEECH -...|                  []| 149.0|[{thumb -> https:...|[{title -> Easy t...|            PenPower|[Office Products,...|{"Product Dimensi...| B098NQ685V|           NULL|                NULL|  NULL|
|         Amazon Home|Assorted Best Sel...|           4.0|           11|                   []|                  []|  NULL|[{thumb -> https:...|                  []|   Apartment 2 Cards|[Office Products,...|{"Product Dimensi...| B00DBSNIC0|           NULL|                NULL|  NULL|
|     Office Products|Paperkraft Handma...|           5.0|            2| [The shimmering c...|                  []|  NULL|[{thumb -> https:...|                  []|          Paperkraft|[Office Products,...|{"Manufacturer":"...| B0771YCWND|           NULL|                NULL|  NULL|
|Tools & Home Impr...|Tall Tin Charity ...|           4.4|            4| [5 Pack Tall Tin ...|[Each tin donatio...| 34.99|[{thumb -> https:...|                  []|    My Charity Boxes|[Office Products,...|{"Manufacturer":"...| B00URTWH7S|           NULL|                NULL|  NULL|
|     Office Products|2022 Cats Sticker...|           4.7|           98| [Stay Organized: ...|                  []|  NULL|[{thumb -> https:...|[{title -> New Ye...|Bright Day Calendars|[Office Products,...|{"Manufacturer":"...| B091BH3XKK|           NULL|                NULL|  NULL|
|     All Electronics|3 Pack Sharp EL23...|           5.0|            8|                   []|[3 Pack Sharp EL2...|  12.4|[{thumb -> https:...|                  []|               Sharp|[Office Products,...|{"Product Dimensi...| B018WY6OSW|           NULL|                NULL|  NULL|
|     All Electronics|LD Products Compa...|           3.9|           78| [The Samsung ML-D...|                  []| 26.12|[{thumb -> https:...|[{title -> Why Ch...|         LD Products|[Office Products,...|{"Product Dimensi...| B001DZWCDO|           NULL|                NULL|  NULL|
|     Office Products|Lateefah Large Mo...|           4.7|          662|[【4-in-1 Mouse Pa...|                  []| 22.99|[{thumb -> https:...|[{title -> Pink M...|            LATEEFAH|[Office Products,...|{"Manufacturer":"...| B09ZV1LFFX|           NULL|                NULL|  NULL|
|     All Electronics|Slim-Fit Dual Lay...|           3.0|            5| [The New iPad Ful...|[This case is mad...|  NULL|[{thumb -> https:...|                  []|        Solid Dealio|[Office Products,...|{"Date First Avai...| B007O3NCGA|           NULL|                NULL|  NULL|
|Industrial & Scie...|Oki Transfer Belt...|           5.0|            1|                   []|                  []|  NULL|[{thumb -> https:...|                  []|            Oki Data|[Office Electroni...|{"Item Weight":"4...| B006582Q2G|           NULL|                NULL|  NULL|
|     Office Products|iSuperb A4 Docume...|           3.4|            7| [Measurement: App...|[Features, 100% B...|  NULL|[{thumb -> https:...|                  []|             iSuperb|[Office Products,...|{"Manufacturer":"...| B0754368LN|           NULL|                NULL|  NULL|
|               Books|30 Halloween to C...|           4.4|            6| ["30 Halloween to...|                  []|  6.99|[{large -> https:...|                  []|V Bookmarks Desig...|[Office Products,...|{"Publisher":"Cre...| 1976289823|           NULL|Paperback – Septe...|  NULL|
|         Amazon Home|Global Industrial...|           3.0|            1|                   []|[Interion® Media ...|541.29|[{thumb -> https:...|                  []|   Global Industrial|[Office Products,...|{"Brand":"Global ...| B0041BSEFC|           NULL|                NULL|  NULL|
|           Computers|CafePress - Forbi...|           4.0|            2| [Fine-textured su...|[The mouse pad is...|  NULL|[{thumb -> https:...|                  []|           CafePress|[Office Products,...|{"Brand":"CafePre...| B00NBGZEKG|           NULL|                NULL|  NULL|
|     Office Products|Hallmark Diwali C...|           4.8|          102| [Send friends or ...|[Send everyone on...|  NULL|[{thumb -> https:...|                  []|            Hallmark|[Office Products,...|{"Manufacturer":"...| B0747TZ7K3|           NULL|                NULL|  NULL|
|     Office Products|HAOCOO Ergonomic ...|           4.5|           76|                   []|                  []|  NULL|[{thumb -> https:...|                  []|              HAOCOO|                  []|{"Manufacturer":"...| B089GHQNDW|           NULL|                NULL|  NULL|
|     Office Products|Keyboard Wrist Re...|           3.9|           12|[🔅【Ergonomic Des...|[Does your wrist ...| 20.99|[{thumb -> https:...|[{title -> Gorill...|           RAUEDWDJS|[Office Products,...|{"Manufacturer":"...| B09BZBHHZ7|           NULL|                NULL|  NULL|
+--------------------+--------------------+--------------+-------------+---------------------+--------------------+------+--------------------+--------------------+--------------------+--------------------+--------------------+-----------+---------------+--------------------+------+
only showing top 20 rows

Xử lý dữ liệu review

In [6]:
meta_df_raw = meta_df
df_data_raw = df_data

In [7]:
df_data = df_data.select("asin","parent_asin","rating","timestamp","user_id","verified_purchase")

In [ ]:
df_data.printSchema()

root
 |-- asin: string (nullable = true)
 |-- parent_asin: string (nullable = true)
 |-- rating: double (nullable = true)
 |-- timestamp: long (nullable = true)
 |-- user_id: string (nullable = true)
 |-- verified_purchase: boolean (nullable = true)

In [ ]:
df_data.count()

12845712

In [ ]:
df_data = df_data.withColumnsRenamed({
    'asin':'product_id',
    'parent_asin':'product_parent',
    'rating':'review_rating',
    'timestamp':'review_date'
})

In [ ]:
user_counts = df_data.groupBy("user_id").agg(count("*").alias("number_rating"))
active_users = user_counts.filter(col("number_rating") >= 5)
active_users = active_users.drop("number_rating")
df_data = df_data.join(active_users, "user_id")

In [ ]:
product_counts = df_data.groupBy("product_id").agg(count("*").alias("number_rating"))
popular_products = product_counts.filter(col("number_rating") >= 5)
popular_products = popular_products.drop("number_rating")
df_data = df_data.join(popular_products, "product_id")

In [ ]:
df_data.count()

2165547

In [ ]:
output_path_rating = "/content/drive/MyDrive/data_parquet/RS/rating_rs.parquet"
df_data.write.mode("overwrite").parquet(output_path_rating)

Xử lý dữ liệu meta

In [ ]:
meta_df.count()

710503

In [ ]:
meta_df.printSchema()

root
 |-- main_category: string (nullable = true)
 |-- title: string (nullable = true)
 |-- features: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- description: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- price: double (nullable = true)
 |-- parent_asin: string (nullable = true)

In [72]:
meta_df = meta_df_raw

In [8]:
meta_df = meta_df.select(
    col("parent_asin").alias("product_id"),
    "title",
    "description",
    "features",
)

In [9]:
meta_df = meta_df.dropDuplicates(["product_id"]) \
                  .withColumn("features",concat_ws(" ", col("features"))) \
                  .withColumn("description",concat_ws(" ", col("description"))) \
                  .withColumn("title",concat_ws(" ", col("title")))

In [29]:
meta_df.show(truncate=False)

+----------+-------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+
|product_id|title                                                                                      |description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |features                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |categories                                                                                              |store                                                             |
+----------+-------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+
|0008529426|Tolkien Calendar 2023                                                                      |The official Tolkien calendar, this year containing 12 stunning paintings from a new generation of artists inspired by the world of Middle-earth.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |Office Products Office & School Supplies Calendars, Planners & Personal Organizers                      |HarperCollins                                                     |
|0008554404|Agatha Christie Marple Calendar 2023                                                       |The first ever official Agatha Christie Calendar celebrates the world's favourite female detective, Miss Jane Maronly, with fourteen paintings by the latest Marple book cover artist, Bill Bragg. Miss Marple was first introduced to readers in a story Christie wrote for The Royal Magazine in 1927 and made her first appearance in a full-length novel in 1930's The Murder at the Vicarage. It is almost 50 years since Agatha Christie's last Miss Marple novel was published, but in 2022 a new book of short stories written by twelve accomplished Christie devotees is bringing the world's favourite female detective back into the limelight. It is entitled simply MARPLE. To coincide with the new book, artist Bill Bragg has painted new covers for all 14 of Agatha Christie's Marple book, and this new wall calendar collects them all in one glorious publication, allowing crime fiction fans to share in the delights of St Mary Mead and beyond throughout 2023!|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |Office Products Office & School Supplies Calendars, Planners & Personal Organizers                      |HarperCollins                                                     |
|0060515597|Body for Life Success Journal                                                              |About the Author Bill Phillips is the founder and editor in chief of Muscle Media ® magazine and the creator of EAS (Experimental and Applied Sciences). Michael D'Orso is the coauthor of Walking With the Wind: A Memoir of the Movement and Winning With Integrity: How to Get What You Want Without Selling Your Soul .                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |New from #1 New York Times bestselling author Bill Phillips comes B ody–for–Life Success Journal . With over three million copies sold and after more than three years on bestseller lists, Body–for–Life is still going strong. People everywhere are discovering that they too have the power to change their body, their mindset, their life. They are discovering that when they make a change, they make a difference –– they become an inspiration to others, a positive example of living a healthy style of life. And now, with this new Success Journal, becoming a Body–for–Life success story is within reach for everyone. More than just a typical log book, this complete Success Journal guides you, day by day, step by step, through the entire 12–week Program. Bill Phillips designed this book to help you stay focused and inspired. Through its pages, he will be with you every step of the way and so will other people who have successfully completed the Program. Each and every day they will support you, encourage you, and help you complete the Program in championship style. When you finish this Success Journal, it will document your success story. However, the real reward will be your new, transformed body and your clear, empowered mindset.                                                                                                                                                                                                                                                                                                                                                                                                                         |Office Products Office & School Supplies Paper                                                          |Bill Phillips (Author)                                            |

In [30]:
total_meta = meta_df.count()

In [31]:
null_meta_counts = meta_df.select([
    sum(
        col(c).isNull().cast('int')
    ).alias(c)
    for c in meta_df.columns
])

null_meta_counts.select([
    concat(
        col(c).cast('string'),
        lit(" ("),
        round(col(c).cast('float') * 100 / total_meta, 2).cast('string'),
        lit("%)")
    ).alias(c)
    for c in meta_df.columns
]).show()

+----------+--------+-----------+--------+----------+--------+
|product_id|   title|description|features|categories|   store|
+----------+--------+-----------+--------+----------+--------+
|  0 (0.0%)|0 (0.0%)|   0 (0.0%)|0 (0.0%)|  0 (0.0%)|0 (0.0%)|
+----------+--------+-----------+--------+----------+--------+

In [32]:
chinese_pattern = r'[\u4e00-\u9fff]'

columns = meta_df.columns

for c in columns:
    count = meta_df.filter(col(c).rlike(chinese_pattern)).count()
    if count > 0:
        print(f"{c}: có {count} dòng chứa tiếng Trung")

title: có 204 dòng chứa tiếng Trung
description: có 148 dòng chứa tiếng Trung
features: có 319 dòng chứa tiếng Trung
store: có 460 dòng chứa tiếng Trung

In [ ]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r'http\S+|www\.\S+', '', text) # Xóa link
    text = re.sub(r'[\u4e00-\u9fff]', ' ', text) # Xóa tiếng trung
    text = re.sub(r"[^a-zA-Z0-9\s/'.]", ' ', text) # Xóa ký tự đặc biệt trừ dấu sở hữu cách và dấu chấm
    text = re.sub(r'\s+', ' ', text) # Xóa khoảng trắng dài
    text = re.sub(r'\b\d{4,}\b', '', text) # Xóa số quá dài
    text = re.sub(r'(\d+)(oz|pack|#)', r'\1_\2', text) # gom những chữ số đi cùng đơn vị
    text = re.sub(r'\b(\d+)\s*pcs?\b', r'\1_piece', text) 
    text = re.sub(r"\.$", "", text) # Xóa dấu chấm kết thúc câu
    return text.strip()
clean_udf = udf(clean_text, StringType())

In [11]:
meta_df= meta_df.withColumn("features",clean_udf(col("features"))) \
                  .withColumn("description",clean_udf(col("description"))) \
                  .withColumn("title",clean_udf(col("title")))

In [12]:
meta_df.show(truncate=False)

+----------+-------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|product_id|title                                                                                      |description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |features                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
+----------+-------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|0000306037|whitecoat clipboard lilac respiratory edition                                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |full size folding medical clipboard lightweight aluminum construction hipaa compliant design to hold sensitive patient documents great for medical students respiratory students respiratory therapists or any healthcare professional powder coated finish for long lasting durability                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|0008529426|tolkien calendar                                                                           |the official tolkien calendar this year containing 12 stunning paintings from a new generation of artists inspired by the world of middle earth                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|0008554404|agatha christie marple calendar                                                            |the first ever official agatha christie calendar celebrates the world's favourite female detective miss jane maronly with fourteen paintings by the latest marple book cover artist bill bragg. miss marple was first introduced to readers in a story christie wrote for the royal magazine in  and made her first appearance in a full length novel in 's the murder at the vicarage. it is almost 50 years since agatha christie's last miss marple novel was published but in  a new book of short stories written by twelve accomplished christie devotees is bringing the world's favourite female detective back into the limelight. it is entitled simply marple. to coincide with the new book artist bill bragg has painted new covers for all 14 of agatha christie's marple book and this new wall calendar collects them all in one glorious publication allowing crime fiction fans to share in the delights of st mary mead and beyond throughout|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|0060515597|body for life success journal                                                              |about the author bill phillips is the founder and editor in chief of muscle media magazine and the creator of eas experimental and applied sciences . michael d'orso is the coauthor of walking with the wind a memoir of the movement and winning with integrity how to get what you want without selling your soul                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |new from 1 new york times bestselling author bill phillips comes b ody for life success journal . with over three million copies sold and after more than three years on bestseller lists body for life is still going strong. people everywhere are discovering that they too have the power to change their body their mindset their life. they are discovering that when they make a change they make a difference they become an inspiration to others a positive example of living a healthy style of life. and now with this new success journal becoming a body for life success story is within reach for everyone. more than just a typical log book this complete success journal guides you day by day step by step through the entire 12 week program. bill phillips designed this book to help you stay focused and inspired. through its pages he will be with you every step of the way and so will other people who have successfully completed the program. each and every day they will support you encourage you and help you complete the program in championship style. when you finish this success journal it will document your success story. however the real reward will be your new transformed body and your clear empowered mindset                                                                                                                                                                                                                                                                                                                                                                                                                      |

In [6]:
output_path_meta = "/content/drive/MyDrive/data_parquet/RS/meta_rs.parquet"
# meta_df.write.mode("overwrite").parquet(output_path_meta)

In [7]:
import pandas as pd
df_meta = pd.read_parquet(output_path_meta)
df_meta

,product_id,title,description,features
0,0000306037,whitecoat clipboard lilac respiratory edition,,full size folding medical clipboard lightweigh...
1,0008529426,tolkien calendar,the official tolkien calendar this year contai...,
2,0008554404,agatha christie marple calendar,the first ever official agatha christie calend...,
3,0060515597,body for life success journal,about the author bill phillips is the founder ...,new from 1 new york times bestselling author b...
4,0061976792,the last little blue envelope 13 little blue e...,about the author maureen johnson is the bestse...,ginny blackstone thought that the biggest adve...
...,...,...,...,...
710498,B0CJ8P5DNS,2_piece folding clipboard waterproof file fold...,2 pack made of three layer foamed polypropylen...,size the size of the pp plastic clipboard is 2...
710499,B0CJRVBJVR,funny valentine's day card romantic anniversar...,funny card make your partner's anniversary a d...,funny card make your partner's anniversary a d...
710500,B0CJT326BB,tools4wisdom planner calendar 15 month dated...,,15 month planner dated october '23 to decembe...
710501,B0CKFL27BK,141a toner cartridge black 2 pack with chip co...,,with chip these 141a toner cartridges 2 pack a...
710502,B0CKHN2FPY,towon large floor standing chalkboard sign wit...,,premium construction the chalkboard surface fe...

In [8]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [9]:
df_meta["clean_text"] = df_meta["title"] + " " + df_meta["features"] + " " + df_meta["description"]

In [18]:
embeddings = model.encode(
    df_meta["clean_text"].tolist(),
    show_progress_bar=True,
    batch_size=64
)
# tràn Ram

Batches:   0%|          | 0/11102 [00:00<?, ?it/s]

In [23]:
import pyarrow as pa
import pyarrow.parquet as pq

batch_size = 50000
writer = None

for start in range(0, len(df_meta), batch_size):
    end = start + batch_size
    batch = df_meta.iloc[start:end].copy()

    embeddings = model.encode(
        batch["clean_text"].tolist(),
        batch_size=64,
        show_progress_bar=True
    )

    batch["embedding"] = embeddings.tolist()

    table = pa.Table.from_pandas(batch[["product_id", "embedding"]])

    if writer is None:
        writer = pq.ParquetWriter("item_embedding.parquet", table.schema)

    writer.write_table(table)

    print(f"Saved batch {start} -> {end}")

if writer:
    writer.close()

Batches:   0%|          | 0/782 [00:00<?, ?it/s]

Saved batch 0 -> 50000

Batches:   0%|          | 0/782 [00:00<?, ?it/s]

Saved batch 50000 -> 100000

Batches:   0%|          | 0/782 [00:00<?, ?it/s]

Saved batch 100000 -> 150000

Batches:   0%|          | 0/782 [00:00<?, ?it/s]

Saved batch 150000 -> 200000

Batches:   0%|          | 0/782 [00:00<?, ?it/s]

Saved batch 200000 -> 250000

Batches:   0%|          | 0/782 [00:00<?, ?it/s]

Saved batch 250000 -> 300000

Batches:   0%|          | 0/782 [00:00<?, ?it/s]

Saved batch 300000 -> 350000

Batches:   0%|          | 0/782 [00:00<?, ?it/s]

Saved batch 350000 -> 400000

Batches:   0%|          | 0/782 [00:00<?, ?it/s]

Saved batch 400000 -> 450000

Batches:   0%|          | 0/782 [00:00<?, ?it/s]

Saved batch 450000 -> 500000

Batches:   0%|          | 0/782 [00:00<?, ?it/s]

Saved batch 500000 -> 550000

Batches:   0%|          | 0/782 [00:00<?, ?it/s]

Saved batch 550000 -> 600000

Batches:   0%|          | 0/782 [00:00<?, ?it/s]

Saved batch 600000 -> 650000

Batches:   0%|          | 0/782 [00:00<?, ?it/s]

Saved batch 650000 -> 700000

Batches:   0%|          | 0/165 [00:00<?, ?it/s]

Saved batch 700000 -> 750000

In [24]:
df_embedding = pd.read_parquet("item_embedding.parquet")

In [26]:
pd.set_option('display.max_colwidth', None)

In [28]:
df_embedding.head()

,product_id,embedding
0,0000306037,"[-0.12555302679538727, 0.09906124323606491, -0.017297780141234398, -0.024684220552444458, -0.02021508663892746, -0.05026417225599289, 0.0727296769618988, 0.06389782577753067, 0.017076391726732254, -0.00015298384823836386, -0.0007342112367041409, 0.08739827573299408, -0.002871930366382003, 0.03246589004993439, -0.07278109341859818, 0.02876361459493637, 0.009181790053844452, -0.02852225862443447, 0.029881885275244713, 0.09569589048624039, 0.0163209717720747, 0.1343345046043396, 0.0061849928461015224, 0.01899814046919346, -0.09267666935920715, 0.07332170009613037, -0.04207342490553856, -0.032755251973867416, 0.057356659322977066, -0.0038867180701345205, 0.09527496993541718, -0.060249410569667816, 0.06423840671777725, 0.02871454320847988, 0.00624098489060998, -0.04811490699648857, 0.018542079254984856, 0.0402732715010643, -0.031183619052171707, 0.010860511101782322, -0.05822526291012764, -0.04071443900465965, -0.05931970849633217, 0.057768139988183975, -0.012367923744022846, 0.026566438376903534, -0.020418480038642883, 0.008516835980117321, 0.01368502713739872, 0.04151761159300804, -0.00612029479816556, -0.07846900075674057, -0.12176377326250076, 0.017172837629914284, -0.03303269296884537, -0.04602867364883423, -0.06591469794511795, -0.033583756536245346, -0.05176196247339249, -0.05358988791704178, -0.06718026101589203, 0.029689984396100044, 0.02193906530737877, 0.045956701040267944, 0.022216083481907845, 0.09513342380523682, -0.03188088908791542, -0.01319093070924282, 0.022253137081861496, -0.03237836807966232, -0.04669223725795746, -0.053393881767988205, 0.01328516099601984, 0.09807851165533066, -0.02927984483540058, 0.02080625481903553, 0.038605380803346634, -0.05249982699751854, 0.008794637396931648, -0.023848069831728935, 0.00816244725137949, -0.019309906288981438, 0.03839047998189926, 0.10271231085062027, 0.005131259560585022, 0.006280186586081982, -0.04158413037657738, 0.0007975035696290433, -0.031870000064373016, -0.05805813893675804, 0.0817800834774971, 0.023890241980552673, 0.05999733507633209, 0.017850108444690704, -0.03926476091146469, -0.009555453434586525, -0.05540744960308075, 0.03298250585794449, 0.0044542583636939526, 0.036864105612039566, ...]"
1,0008529426,"[-0.004104066174477339, -0.019372206181287766, 0.030008632689714432, -0.025627896189689636, 0.0734945684671402, -0.012533874250948429, -0.1428128331899643, -0.01496238261461258, 0.012759395875036716, -0.020985914394259453, -0.0994969978928566, -0.0223526693880558, 0.032245934009552, -0.03654516860842705, 0.0012051602825522423, 0.002953690243884921, -0.07397463172674179, -0.020135648548603058, 0.033934611827135086, -0.07294750958681107, 0.004179357085376978, 0.020791534334421158, -0.0036205884534865618, 0.036664485931396484, 0.04284307360649109, 0.005140196532011032, 0.03963885456323624, -0.0504218153655529, -0.014560461975634098, 0.0673854872584343, -0.0076028723269701, 0.08753211796283722, -0.025127587839961052, -0.024024875834584236, -0.009188895113766193, 0.09972129017114639, -0.10641554743051529, 0.01412620022892952, 0.002991184126585722, -0.07339416444301605, -0.023318763822317123, -0.05658077448606491, 0.04018841311335564, -0.0645633265376091, -0.006079362239688635, -0.0007945604156702757, -0.07878988236188889, 0.03337268531322479, -0.041728485375642776, 0.07915887981653214, 0.029119368642568588, -0.07614865154027939, -0.03931021690368652, -0.040560413151979446, 0.10766872018575668, -0.007918953895568848, -0.1288386583328247, -0.09349136054515839, 0.051570624113082886, 0.026260213926434517, -0.05980580300092697, 0.022648675367236137, -0.04820971563458443, 0.014039985835552216, -0.03430285304784775, 0.05124075710773468, 0.062472887337207794, 0.002061366569250822, 0.014891651459038258, -0.11028030514717102, 0.0057808286510407925, -0.010913630947470665, -0.007321578450500965, -0.0745648592710495, 0.04448802396655083, 0.042412251234054565, -0.11121100187301636, 0.007698793895542622, -0.043278735131025314, -0.11757756769657135, 0.032631706446409225, 0.04571905359625816, 0.03127314895391464, -0.008527195081114769, 0.015156288631260395, 0.02312280796468258, -0.07204677164554596, 0.022349419072270393, -0.09495697915554047, -0.006596743129193783, 0.07789988815784454, -0.028549881651997566, 0.021805793046951294, 0.03489048033952713, -0.056380629539489746, 0.06789197772741318, 0.04332370683550835, -0.045036688446998596, 0.04376355558633804, -0.010309312492609024, ...]"
2,0008554404,"[0.006474583875387907, 0.019247207790613174, 0.01463211327791214, 0.06998392939567566, 0.09151773154735565, 0.13172215223312378, -0.07539530098438263, 0.026581045240163803, -0.01701406203210354, -0.02731691300868988, -0.005702562630176544, 0.0468859001994133, 0.035737376660108566, -0.060851674526929855, 0.016057707369327545, -0.01898934692144394, -0.08929139375686646, -0.04661884903907776, 0.052769556641578674, 0.05184641107916832, -0.05062808468937874, -0.054206136614084244, -0.011351416818797588, -0.04336228966712952, 0.02839348465204239, -0.05395099148154259, -0.024051424115896225, -0.06618483364582062, -0.06890137493610382, 0.06173185259103775, 0.003618054324761033, 0.05378701165318489, 0.08317907899618149, 0.016027236357331276, 0.05043639615178108, -0.08275235444307327, 0.03733328357338905, -0.01345189567655325, 0.08485344052314758, -0.04248343035578728, -0.01823357865214348, -0.04119255021214485, -0.02543867751955986, 0.017849193885922432, -0.029765060171484947, -0.05252585560083389, 0.03628247603774071, 0.092841736972332, -0.02603575401008129, 0.0022356228437274694, -0.0633561909198761, -0.04408612847328186, -0.09066194295883179, -0.004483931697905064, 0.055163513869047165, -0.008103404194116592, -0.06759124994277954, -0.00535807479172945, -0.027920305728912354, -0.06656689196825027, -0.06278117746114731, 0.057138893753290176, -0.026822548359632492, -0.02293587476015091, 0.010056442581117153, 0.007324050646275282, 0.007358738221228123, 0.0661902129650116, 0.10412835329771042, 0.07250112295150757, -0.010169899091124535, 0.052672889083623886, -0.013925421983003616, 0.05848345905542374, 0.05642043426632881, 0.03134242445230484, 0.024645889177918434, -0.06338459998369217, -0.030917387455701828, -0.05154050514101982, -0.15099366009235382, -0.05423203855752945, -0.035808976739645004, 0.050489988178014755, 0.002753989305347204, -0.036778002977371216, -0.03864437714219093, -0.014101657085120678, 0.00028144687530584633, -0.016650594770908356, 0.02470795251429081, -0.04592312127351761, -0.05735664814710617, -0.056980621069669724, -0.05555567145347595, 0.008369330316781998, -0.05730481073260307, -0.005189390387386084, 0.0037679560482501984, 0.00197050254791975, ...]"
3,0060515597,"[0.014203422702848911, 0.055674996227025986, -0.024391086772084236, 0.018833933398127556, 0.03467826545238495, -0.06682100147008896, 0.030298154801130295, 0.0035575185902416706, -0.03900153934955597, 0.0009410607162863016, 0.006506561301648617, 0.1021714061498642, -0.009556682780385017, 0.0015808464959263802, 0.03861919045448303, -0.012446417473256588, 0.003288229927420616, -0.019238393753767014, -0.06217993423342705, 0.10552456974983215, 0.026504136621952057, 0.008556559681892395, 0.048307184129953384, 0.036737509071826935, -0.08019310235977173, 0.014263216406106949, -0.07279448211193085, -0.07283365726470947, -0.02490122988820076, -0.07147017866373062, 0.03931734338402748, -0.02733294852077961, 0.004643190186470747, -0.02923295460641384, -0.02194949798285961, 0.04990273341536522, 0.0229909960180521, -0.014357621781527996, -0.08342712372541428, -0.025870421901345253, -0.05170663073658943, -0.09927858412265778, 0.011381682939827442, 0.049241770058870316, 0.03786838799715042, -0.031342145055532455, -0.08271696418523788, 0.0017175929388031363, 0.0416385717689991, 0.004276755731552839, -0.09992358088493347, -0.0884825736284256, 0.04686423018574715, -0.0691460445523262, 0.04093675687909126, 0.1273692101240158, -0.018756508827209473, 0.02228640764951706, -0.0846865177154541, -0.08473356068134308, -0.0008941354462876916, 0.021277902647852898, -0.04817303642630577, 0.018646905198693275, 0.022864336147904396, -0.02654050663113594, 0.05555262789130211, 0.01785627193748951, -0.05356278270483017, -0.03474728390574455, -0.04622760787606239, -0.08644711971282959, -0.0022130918223410845, 0.03924773260951042, 0.13285928964614868, 0.10326088219881058, -0.007512250915169716, -0.016818124800920486, 0.004878590814769268, 0.02558685839176178, -0.009961660020053387, 0.025028685107827187, -0.022518275305628777, 0.013636229559779167, -0.0930481031537056, 0.007501265034079552, 0.004553202074021101, 0.055627066642045975, 0.008918958716094494, 0.01256877277046442, -0.01320237759500742, 0.04168492928147316, 0.0072412737645208836, -0.03965628892183304, -0.06109645962715149, 0.09160415083169937, -0.1216578334569931, -0.006122804246842861, 0.008686989545822144, 0.006671226117759943, ...]"
4,0061976792,"[-0.000988147919997573, -0.06483323872089386, 0.055228881537914276, 0.007339356932789087, -0.03861672431230545, 0.10422910749912262, -0.010805506259202957, -0.015048348344862461, 0.021779537200927734, 0.02920030616223812, 0.036113739013671875, 0.07965186983346939, -0.039197888225317, -0.000570948061067611, -0.032845184206962585, 0.1360660344362259, -0.022631648927927017, -0.010884016752243042, -0.0837862640619278, -0.002311713295057416, -0.013843702152371407, 0.03582576662302017, 0.049802228808403015, 0.057471249252557755, -0.040263764560222626, -0.008882474154233932, -0.04532046988606453, -0.041729796677827835, 0.010367807000875473, 0.061199456453323364, -0.07876073569059372, 0.06160150095820427, -0.028399936854839325, -0.004794706124812365, 0.0914592370390892, 0.033374082297086716, 0.030681248754262924, 0.007803709711879492, 0.040169619023799896, -0.03863563761115074, -0.08246008306741714, -0.014245462603867054, -0.06665465980768204, -0.006054911762475967, 0.0361991822719574, -0.10943898558616638, -0.018204674124717712, -0.03851791098713875, 0.047215040773153305, -0.008806515485048294, 0.0747326910495758, 0.000966121384408325, -0.012405053712427616, 0.009152911603450775, -0.004806910641491413, -0.02479533851146698, -0.03950737416744232, -0.012265977449715137, 0.03624650090932846, 0.002157552633434534, -0.028777142986655235, -0.03053480014204979, -0.10862214118242264, -0.019784368574619293, 0.01837446354329586, 0.026063118129968643, -0.011230451054871082, 0.04875835031270981, -0.06324327737092972, -0.019664881750941277, -0.049213215708732605, -0.0008877194486558437, -0.06376924365758896, 0.029772374778985977, 0.05926474183797836, 0.022428540512919426, 0.017525259405374527, -0.07387704402208328, -0.10303745418787003, 0.042902398854494095, -0.050509143620729446, -0.07862538844347, 0.052559949457645416, 0.08755151927471161, -0.030006306245923042, -0.0413447842001915, -0.027880841866135597, -0.03343396633863449, -0.08545763045549393, -0.02901437133550644, -0.040239784866571426, 0.027560051530599594, 0.019432004541158676, 0.0533195398747921, -0.032155755907297134, -0.01676849089562893, 0.024193283170461655, 0.015582764521241188, 0.006694520357996225, 0.031775880604982376, ...]"